### ISSUE TITLE
Project: record past/current maintenance frequency?

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-dam-analogues#45]
Per Matt Orr via email, 3/3/18.

Under "Maintenance" maybe have two categories: "past maintenance / frequency" (e.g. monthly, yearly) and "future planned maintenance / frequency."

**Comment by ybakos** [comment]
What do you think about this, @webernick79 ?

**Comment by webernick79** [comment]
Hmmm......See my next comment also about using term "adaptive management" instead of "maintenance". We might just have a checkbox for "Adaptive Management" and then say "Number of Years".

However, we need to keep this simple. We could keep adding attributes, but most important thing is just the where, who, and what of each project.
