### ISSUE TITLE
Cant sign in user via rspec and factory_bot

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/beaver-dam-analogues#6]
Get an invalid login, when expecting a successful login

**Comment by ybakos** [comment]
We run the test and see it fail. The failure notice I first see is that there is no "Log in" button. It's "Sign In." I fix that [here](fd1c66c11515d1de07fb2e0005f52df9c4300bf5).

The next failure is this one, which is what I believe you were seeing:

![screen shot 2018-01-25 at 8 13 37 pm](https://user-images.githubusercontent.com/5502/35425051-d6d51744-020c-11e8-9dd0-048fc667acef.png)

So we investigate what's happening right before that with a breakpoint:

![screen shot 2018-01-25 at 8 13 46 pm](https://user-images.githubusercontent.com/5502/35425064-f81a877c-020c-11e8-8e39-4268721b46c3.png)

And inspect the page content to determine, "well what content _does_ it have if it does not have an alert with the success message?"

![screen shot 2018-01-25 at 8 14 04 pm](https://user-images.githubusercontent.com/5502/35425080-17972272-020d-11e8-89f4-04521ddf0c07.png)

And we see that it does have the select message, but in a `.notice` element.

![screen shot 2018-01-25 at 8 14 21 pm](https://user-images.githubusercontent.com/5502/35425123-5d7479c0-020d-11e8-9a17-9b9ecad5f0e4.png)

See ce45f526941178798ea543fc4bbb14def6a33ba1 .

**Comment by ybakos** [comment]
@nathanstruhs This is fixed, see the issue here in GH for a narrative.

Note that I also added `:type => :feature` to the test config because:

- Rspec infers the test type from the directory, and _system_ tests by default tell Capybara to switch to the selenium webdriver (it seems)
- I wanted a "faster" test since there's no js drama
- Rspec uses the default Capybara webdriver for _feature_ tests

So by adding the `:type => :feature` to the test declaration this tells rspec to run it as a "feature" test.

You can explain the difference between feature and system tests to me. And perhaps try running the test suite without that `:type => :feature` annotation and let me know if it fails using the selenium webdriver.

**Comment by ybakos** [comment]
@nathanstruhs Ok, here's an explanation of the bug.

First, the bottom line is to use the rack driver instead of selenium for speed. If you've got a UX that relies on some JS, then use selenium. (General rule of thumb.)

Given that I run the test as a system test w/ selenium,
When a User object is created in the test,
And I verify its creation in the test with a breakpoint and see that `User.count == 1`,
There really is no User record created in the database, because
A breakpoint in the `User#find_first_by_auth_conditions` where I call `User.count` returns `0`,
And I can open the database directly (pgsql) and see that _0_ User records exist in the *bdadb_test* database.

In short, we verified the existence of the User object in the test methods but the object was "missing" in the `User#find_first_by_auth_conditions` method.

The SO post we saw that said "set `config.use_transactional_fixtures = false` was actually the solution, but didn't explain why, nor explain the side effects.

By default (with `use_transactional_fixtures = true`) rspec test methods do indeed create objects in the database but _they do not commit the transaction_. This is how rspec starts each test with an "empty" database. Within the scope of the test suites' process, it sees the non-committed stuff in the database. (Hence `User.count == 1`). At the end of the test, it just rolls back the transaction, so there's no data in the db to interfere with the next test methods.

But if you start up a console in the test env (`RAILS_ENV=test rails c`) you'll find that the User count is 0. And if you inspect the db table itself, you'll find the _users_ table has no records. That's because the db transaction from the test is not committed. No other process / db connection "sees" the database operations from the test process' db transaction.

Same goes for the selenium process - it's in an entirely separate process, with its own db connection, so doesn't have any visibility into the rspec test process' connection/transaction.

By setting `use_transactional_fixtures = false`, rspec will indeed commit each database operation. This enables other processes to 'see' the data in the db, since it's actually committed. The problem is, subsequent test methods now no longer have a clean/empty database. So you have to manually clean up the database between each test - or use a gem like *database_cleaner* that will do it for you.

Manual database cleaning, or using a gem that does it, is only necessary when you aren't using transactional fixtures.

I recommend sticking with transactional fixtures until you reach a situation that demands that you can't.

The rack_driver tests pass because they don't fire up any external process like selenium. Everything is still within the scope of one process, db connection, and db transaction.

**Comment by ybakos** [comment]
Also see
https://stackoverflow.com/questions/6154687/rails-integration-test-with-selenium-as-webdriver-cant-sign-in
and
 http://www.virtuouscode.com/2012/08/31/configuring-database_cleaner-with-rails-rspec-capybara-and-selenium/
and
https://stackoverflow.com/questions/12326096/capybara-selenium-fault-and-redirect-example-com-when-without-everything-is-gre/12330557#12330557
